name = "palabres"
version = "1.0.2"

description = "Opinionated logger for Gleam, targetting both BEAM and JS"
licences = ["MIT"]
internal_modules = ["palabres/internals", "palabres/internals/*"]

[[links]]
title = "Sponsor"
href = "https://github.com/sponsors/ghivert"

[repository]
type = "github"
user = "ghivert"
repo = "palabres"
path = "palabres"
tag-prefix = "palabres_"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleeunit = ">= 1.4.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
